name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui --ignore-failed-sources
 
      - name: Herstel afhankelijkheden
        run: dotnet restore Grocery.App/Grocery.App.csproj
 
      - name: Bouw de applicatie (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release
 
      - name: Bouw en voer tests uit
        run: dotnet test --configuration Release --no-build --verbosity normal
